
CXXFLAGS := -std=c++14 -O3 -g -Wall $(CXXFLAGS)

all: 1 2 3 4

1: 1.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

2: 2.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

3: 3.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

4: 4.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

clean:
	rm -f 1 2 3 4
