
CXXFLAGS := -std=c++14 -O3 -g -Wall $(CXXFLAGS)

all: 1 2 3 4 7 8 9 10 11 12 14 15

1: 1.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

2: 2.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

3: 3.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

4: 4.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

8: 8.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

7: 7.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

9: 9.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

10: 10.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

11: 11.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

12: 12.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

14: 14.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

15: 15.cpp
	$(CXX) $(CFLAGS) $(CXXFLAGS) -o $@ $^

clean:
	rm -f 1 2 3 4 7 8 9 10 11 12 14 15
